kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: idp-project-cluster
nodes:
  - role: control-plane
    # Uncomment the following lines in case you want to persist data outside the
    # kind cluster
    # extraMounts:
    # - hostPath: PATH-TO-REPO/platform-infra/volumes
    #   containerPath: /volumes
  - role: worker
  - role: worker
