kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: idp-project-cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: PATH-TO-REPO/platform-infra/database/volumes
    containerPath: /volumes
- role: worker
- role: worker
