apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-api
spec:
  selector:
    matchLabels:
      app: io-api
  template:
    metadata:
      labels:
        app: io-api
    spec:
      containers:
        - name: io-api
          image: idpuser/io-api:latest
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 6061
              path: /
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6061
              name: io-api-port
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user-creds
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-creds
                  key: password
            - name: DB_NAME
              value: steem
            - name: DB_HOST
              value: postgres-rw
            - name: DB_PORT
              value: "5432"
