apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  labels:
    app: pgadmin
    type: data
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      app: pgadmin
      type: data
