apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers-cfg
  labels:
    app: pgadmin
    type: servers-cfg
data:
  servers.json: |
    {
      "Servers": {
        "1": {
            "Name": "Steem",
            "Group": "Servers",
            "Port": 5432,
            "Username": "admin",
            "Host": "postgres-rw",
            "SSLMode": "prefer",
            "MaintenanceDB": "postgres"
        }
      }
    }
