apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-data
  labels:
    app: pgadmin
    type: data
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/pgadmin-data

