apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    app: postgres
    type: data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /volumes/data
