apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-cfg
  labels:
    app: postgres
    type: init
data:
  init.sql: |
    SELECT current_user;

    CREATE TABLE IF NOT EXISTS users (
      uid SERIAL PRIMARY KEY,
      email VARCHAR(256) UNIQUE,
      passwd VARCHAR(256) NOT NULL,
      is_publisher BOOLEAN DEFAULT FALSE,
      is_admin BOOLEAN DEFAULT FALSE
    );

    CREATE TABLE IF NOT EXISTS wallets (
      uid INTEGER PRIMARY KEY REFERENCES users (uid) ON DELETE CASCADE,
      balance INTEGER DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS games (
      gid SERIAL PRIMARY KEY,
      name VARCHAR(256) UNIQUE,
      description VARCHAR(256),
      price INTEGER NOT NULL,
      publisher INTEGER REFERENCES users (uid),
      status VARCHAR(256) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS purchases (
      pid SERIAL PRIMARY KEY,
      game_id INTEGER REFERENCES games (gid),
      user_id INTEGER REFERENCES users (uid),
      date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      hours_played INTEGER DEFAULT 0
    );
