apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-cfg
  labels:
    app: postgres
    type: init
data:
  # TODO: replace this dummy init script with the actual one
  init.sql: |
    SELECT current_user;

    CREATE TABLE TARI
    (
        ID          SERIAL PRIMARY KEY NOT NULL,
        NUME_TARA   VARCHAR(30) UNIQUE NOT NULL CHECK (NUME_TARA <> ''),
        LATITUDINE  DOUBLE PRECISION   NOT NULL CHECK (LATITUDINE >= -90 AND LATITUDINE <= 90),
        LONGITUDINE DOUBLE PRECISION   NOT NULL CHECK (LONGITUDINE >= -180 AND LONGITUDINE <= 180)
    );

    CREATE TABLE ORASE
    (
        ID          SERIAL PRIMARY KEY NOT NULL,
        NUME_ORAS   VARCHAR(30)        NOT NULL CHECK (NUME_ORAS <> ''),
        LATITUDINE  DOUBLE PRECISION   NOT NULL CHECK (LATITUDINE >= -90 AND LATITUDINE <= 90),
        LONGITUDINE DOUBLE PRECISION   NOT NULL CHECK (LONGITUDINE >= -180 AND LONGITUDINE <= 180),
        ID_TARA     INTEGER REFERENCES TARI (ID) ON DELETE CASCADE,
        UNIQUE (NUME_ORAS, ID_TARA)
    );

    CREATE TABLE TEMPERATURI
    (
        ID      SERIAL PRIMARY KEY NOT NULL,
        VALOARE DOUBLE PRECISION   NOT NULL,
        DATA    BIGINT             NOT NULL,
        ID_ORAS INTEGER REFERENCES ORASE (ID) ON DELETE CASCADE,
        UNIQUE (ID_ORAS, DATA)
    );

