apiVersion: apps/v1
kind: Deployment
metadata:
  name: steem-api
spec:
  selector:
    matchLabels:
      app: steem-api
  template:
    metadata:
      labels:
        app: steem-api
    spec:
      containers:
        - name: steem-api
          image: idpuser/steem-api:latest
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 5031
              path: /health
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5031
              name: steem-api-port
          env:
            - name: IO_API_HOST
              value: "io-svc"
            - name: IO_API_PORT
              value: "6061"
            - name: AUTH_API_HOST
              value: "auth-svc"
            - name: AUTH_API_PORT
              value: "5050"
