apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: idpuser/auth-api:latest
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 5050
              path: /health
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5050
              name: auth-api-port
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-api-jwt-secret
                  key: JWT_SECRET
                  optional: false
            - name: IO_API_HOST
              value: "io-api"
            - name: IO_API_PORT
              value: "6061"
