apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: steem-vs
spec:
  host: idp.steem.com
  tls:
    secret: steem-tls-certs
  upstreams:
    - name: auth-api
      service: auth-svc
      port: 5050
    - name: steem-api
      service: steem-svc
      port: 5031
  routes:
    - path: /auth
      action:
        proxy:
          upstream: auth-api
          rewritePath: /
    - path: /api
      action:
        proxy:
          upstream: steem-api
          rewritePath: /
